apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
spec:
  replicas: 1
  selector:
    matchLabels:
      tier: backend
    matchExpressions:
      - {key: tier, operator: In, values: [backend]}
  template:
    metadata:
      labels:
        app: web-service
        tier: backend
    spec:
      containers:
      - name: web-service
        image: tonywang/webservice
        imagePullPolicy: IfNotPresent
        volumeMounts:
        - mountPath: /var/run/docker.sock
          name: docker-socket
        ports:
        - containerPort: 8090
      volumes:
      - name: docker-socket
        hostPath:
          path: /var/run/docker.sock
          type: Socket
