apiVersion: v1
kind: Pod
metadata:
  name: web-service-hostpath
  labels:
    app: web-service
    vol: hostpath
spec:
  containers:
  - name: web-service
    image: tonywang/webservice
    imagePullPolicy: IfNotPresent
    volumeMounts:
    - mountPath: /usr/src/share
      name: k8s-docker-hostpath
    - mountPath: /var/run/dockershim.sock
      name: k8s-docker-socket
    ports:
    - containerPort: 8080
  volumes:
  - name: k8s-docker-hostpath
    hostPath:
      path: /home/tonywang/share
      type: DirectoryOrCreate
  - name: k8s-docker-socket
    hostPath:
      path: /var/run/dockershim.sock
      type: Socket
  affinity:
    podAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
      - labelSelector:
          matchLabels:
            vol: hostpath
          matchExpressions:
          - {key: vol, operator: In, values: [hostpath]}
        topologyKey: "kubernetes.io/hostname"
